// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwbhttdmltsctblqzxuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Ymh0dGRtbHRzY3RibHF6eHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzY5MzEsImV4cCI6MjA2OTExMjkzMX0.mI2eqVczPEBnlA_JjQIthL3gPC-RJpsB7liKryHQoLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});