name: MegaLinter
on:
  pull_request:
  push:

permissions:
  contents: write   # required so fixes can be committed or PRs opened
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history so fixes can be pushed
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v7
        env:
          # Choose when fixes happen: all | push | pull_request | none
          APPLY_FIXES_EVENT: pull_request
          # Choose how fixes are delivered: commit | pull_request
          APPLY_FIXES_MODE: commit
          # Optional: speed up by only checking changed files on PRs
          # MEGALINTER_CONFIG: .mega-linter.yml
